stages:
  - build
#   - test

build_debug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk

# unit_tests:
#   stage: test
#   script:
#     - ./gradlew test